<a href="https://colab.research.google.com/github/fanbyprinciple/ML-experiments/blob/master/tf_quickstart_beginner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [3]:
mnist  = tf.keras.datasets.mnist

In [4]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [5]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [7]:
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Flatten(input_shape=(28,28)),
                                    tf.keras.layers.Dense(128, activation='relu'),
                                    tf.keras.layers.Dropout(0.2),
                                    tf.keras.layers.Dense(10)
])

In [8]:
predictions = model(x_train[:1]).numpy()

In [9]:
predictions

array([[ 0.2568362 ,  0.2705673 ,  0.45390132, -0.5847111 , -0.34318146,
         0.3605727 , -1.3911841 , -0.36320037,  0.30959815,  0.19786389]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.12425342, 0.12597132, 0.15131871, 0.05355858, 0.06819052,
        0.13783532, 0.02391015, 0.06683899, 0.1309853 , 0.11713778]],
      dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [12]:
loss_fn(y_train[:1], predictions).numpy()

1.9816957

In [13]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [14]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2977 - accuracy: 0.9129
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1430 - accuracy: 0.9581
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1067 - accuracy: 0.9680
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0878 - accuracy: 0.9732
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0754 - accuracy: 0.9771


In [15]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0775 - accuracy: 0.9768


[0.07749713957309723, 0.9768000245094299]

In [16]:
probability_model = tf.keras.Sequential([
                                         model,
                                         tf.keras.layers.Softmax()
])

In [17]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.24530640e-07, 1.70126047e-08, 3.48684921e-07, 2.25909796e-04,
        5.27107568e-12, 3.47108966e-07, 3.22366975e-15, 9.99770701e-01,
        9.26321491e-07, 1.28246802e-06],
       [1.14324259e-07, 5.93633631e-05, 9.99585330e-01, 3.41724168e-04,
        1.16763889e-17, 1.31765746e-05, 1.15660566e-08, 1.17960587e-13,
        1.87272590e-07, 3.95613768e-15],
       [3.46962167e-07, 9.98885810e-01, 1.89688653e-04, 1.32592277e-05,
        1.99957831e-05, 1.11697345e-05, 1.32841496e-05, 7.87769502e-04,
        7.86342207e-05, 1.10148370e-07],
       [9.99981165e-01, 4.37184004e-11, 7.25860264e-06, 2.57383732e-07,
        8.13984169e-09, 9.27289511e-06, 9.04303988e-07, 2.43658832e-07,
        3.88642825e-08, 9.05399077e-07],
       [3.77512551e-05, 4.50390942e-08, 4.89438025e-05, 1.65593462e-07,
        9.94307816e-01, 4.17510000e-06, 1.36272974e-05, 6.99534488e-04,
        3.76962853e-05, 4.85028885e-03]], dtype=float32)>

In [24]:
print(probability_model(x_test[:5]), y_test[:5])

tf.Tensor(
[[4.24530640e-07 1.70126047e-08 3.48684921e-07 2.25909796e-04
  5.27107568e-12 3.47108966e-07 3.22366975e-15 9.99770701e-01
  9.26321491e-07 1.28246802e-06]
 [1.14324259e-07 5.93633631e-05 9.99585330e-01 3.41724168e-04
  1.16763889e-17 1.31765746e-05 1.15660566e-08 1.17960587e-13
  1.87272590e-07 3.95613768e-15]
 [3.46962167e-07 9.98885810e-01 1.89688653e-04 1.32592277e-05
  1.99957831e-05 1.11697345e-05 1.32841496e-05 7.87769502e-04
  7.86342207e-05 1.10148370e-07]
 [9.99981165e-01 4.37184004e-11 7.25860264e-06 2.57383732e-07
  8.13984169e-09 9.27289511e-06 9.04303988e-07 2.43658832e-07
  3.88642825e-08 9.05399077e-07]
 [3.77512551e-05 4.50390942e-08 4.89438025e-05 1.65593462e-07
  9.94307816e-01 4.17510000e-06 1.36272974e-05 6.99534488e-04
  3.76962853e-05 4.85028885e-03]], shape=(5, 10), dtype=float32) [7 2 1 0 4]
